// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://xnnhoqvtooyipjvyfvms.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhubmhvcXZ0b295aXBqdnlmdm1zIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjM3NzM2NTQsImV4cCI6MjA3OTM0OTY1NH0.D6s8mFF5y1P7xPsfD030lgFAEMKJKfo0mC7laDbzmsg";

// ✅ Main Supabase client (without Database type)
export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: window.sessionStorage,
    persistSession: true,
    autoRefreshToken: false,
    detectSessionInUrl: false,
    flowType: 'pkce',
  },
});

// ✅ Static client with custom storage
const customStorage = {
  getItem: (key: string) => {
    try { return sessionStorage.getItem(key); } catch { return null; }
  },
  setItem: (key: string, value: string) => {
    try { sessionStorage.setItem(key, value); } catch { /* ignore */ }
  },
  removeItem: (key: string) => {
    try { sessionStorage.removeItem(key); } catch { /* ignore */ }
  },
};

export const supabaseStatic = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: customStorage,
    persistSession: true,
    autoRefreshToken: false,
    detectSessionInUrl: false,
    flowType: 'pkce',
    storageKey: 'sb-static-auth-token',
  },
});

export const getSession = async () => {
  try {
    const { data: { session }, error } = await supabaseStatic.auth.getSession();
    if (error) {
      console.warn('Get session error:', error.message);
      return null;
    }
    return session;
  } catch (error) {
    console.warn('Get session failed:', error);
    return null;
  }
};

export const getUser = async () => {
  try {
    const { data: { user }, error } = await supabaseStatic.auth.getUser();
    if (error) {
      console.warn('Get user error:', error.message);
      return null;
    }
    return user;
  } catch (error) {
    console.warn('Get user failed:', error);
    return null;
  }
};

export const isAuthenticated = async () => {
  const user = await getUser();
  return !!user;
};