// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xnnhoqvtooyipjvyfvms.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhubmhvcXZ0b295aXBqdnlmdm1zIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjM3NzM2NTQsImV4cCI6MjA3OTM0OTY1NH0.D6s8mFF5y1P7xPsfD030lgFAEMKJKfo0mC7laDbzmsg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});